# Generated by Django 4.1.2 on 2022-10-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
